name: Bug Report
description: Report a problem in Neorg
labels: [bug]
body:

  - type: checkboxes
    id: faq-prerequisite
    attributes:
      label: Prerequisites
      options:
        - label: I am using either 0.7 stable with the `0.0.12` tag or the latest compiled Neovim version
          required: true
        - label: I am using the latest version of the plugin
          required: true

  - type: input
    attributes:
      label: "Neovim Version"
      description: "`nvim --version`:"
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Neorg setup"
      description: |
        - Copy your entire "require("neorg").setup" function
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Actual behavior"
      description: "A description of actual behavior. May optionally include images or videos."
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Expected behavior"
      description: "A description of the behavior you expected."
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Steps to reproduce"
      description: "Please describe how we can reproduce the issue. Ideally you should provide the contents of a norg file which shows the issue."
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Potentially conflicting plugins"
      description: "Other plugins you are using which you think could potentially be conflicting with neorg."

  - type: textarea
    attributes:
      label: "Other information"
      description: "Other information that could be helpful with debugging."

  - type: dropdown
    id: help
    attributes:
      label: "Help"
      description: "Would you be able to resolve this issue by submitting a pull request?"
      options:
        - "Yes"
        - "Yes, but I don't know how to start. I would need guidance (check question below)"
        - "No"

  - type: textarea
    attributes:
      label: "Implementation help"
      description: "If you selected yes in the last question please specify what you would need help with in order to implement this?"

